version: '3.8'
services: 
  api-escalamiento-proyecto-servicio: 
    image: camilo97/api-escalamiento-micro-servicio:v1
    build: 
      context: .
    ports:
      - "4004-4019:5510"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=5510
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - api-escalamiento-net

  balanceador-api-escalamiento-proyecto-servicio:
    container_name: balanceador-api-escalamiento-proyecto-servicio
    image: camilo97/balanceador:v1
    build:
      context: ./../balanceador
    ports:
      - "4020:80"
    networks:
      - api-escalamiento-net

networks:
  api-escalamiento-net: